### ISSUE TITLE
After init-remote says remote is ready for deliveries get error remote does not look like a bare repo

### ISSUE THREAD

**Issue by drahamim** [arnoo/git-deliver#42]
I am not sure why this error occurs. 

I also couldn't get --init and --init-remote to work without first creating and doing a git init bare to get git-deliver to say that the remote is ready for deliveries. 
Is there something I am doing wrong?

Let me know if I need to provide more details

**Comment by magnusstubman** [comment]
This is still a problem for me.

**Comment by arnoo** [comment]
This is fixed by commit https://github.com/arnoo/git-deliver/commit/faab3519970bc72a6cc4848765859e72ce1b9c64 which adds tilde expansion for remote URLs.
